import type { Metadata } from "next";
import 'remixicon/fonts/remixicon.css'
import "./globals.css";
import Navbar from "./{Components}/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"w-full h-full flex flex-col p-0 m-0 box-border font-[Future] bg-darkblack text-primary " + `antialiased`}>
        <header>
          <Navbar />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
